# This file shows the skeleton of r3build.toml.
# It is structured with a bunch of sections that contain multiple keys and values.

# Values in this file are the default value of corresponding keys.


[log]
# `log` section defines what r3build will output.

# all (bool)
#  - Turn on all event logs.
#  - Notice: it overrides all other log flags.
#
# accepted_events (bool)
#  - Show all incoming events except rate-limited ones.
#
# rate_limited_events (bool)
#  - Show rate-limited events.
#  - Hint: rate-limit duration is set by `event.rate_limit_duration`.
#
# filtered_events (bool)
#  - Show filtered events.
#
# dispatched_events (bool)
#  - Show events dispatched to processors.
#
# processor_output (bool)
#  - Show the output of the executed processor.
#
# result (bool)
#  - Show if the run was successful or not.
#
# time (bool)
#  - Show target's execution time.

all = false
accepted_events = false
rate_limited_events = false
filtered_events = false
dispatched_events = false
processor_output = true
result = true
time = true


[event]
# `event` section defines how r3build handle events.

# rate_limit_duration (float)
#  - Duration for dropping (debouncing) events that occurred so closely (the unit is second).
#
# ignore_events_while_run (bool)
#  - Ignore events occurred while a processor is running.
#  - Disabling this flag may result in a never-ending execution loop. Disable with care.

rate_limit_duration = 0.01
ignore_events_while_run = true


[[target]]
# `target` array-of-tables defines jobs.
#  - What to watch (match and exclude files with glob and regex)
#  - What processor to execute
#  - How the processor process things
# ... and etc.

# processor (str)  *REQUIRED*
#  - The ID of the processor for the target.
#  - To see the full list of processors, run `python -m r3build --processors`.
#  - For processor-specific configs, see the following sections.
#
# name (str)
#  - Human-readable name of the target.
#
# when (Union[List[str], str])
#  - One or more types of events to trigger this job.
#  - The job will accept all types of events if it's ommitted.
#  - Available choices are "moved", "deleted", "created", "modified".
#
# path (str)
#  - The root directory to watch.
#  - Any file events (move, delete, create, modify) inside this directory will be reported to r3build recursively.
#
# glob (Union[List[str], str])
#  - One or more glob patterns to match the file path.
#  - The target will be triggered if one or more patterns match to it.
#
# glob_exclude (Union[List[str], str])
#  - One or more glob patterns to exclude. The effect is opposite to `glob`.
#  - The target won't be triggered if one or more patterns match to it.
#
# regex (Union[List[str], str])
#  - One or more regular expression patterns to match the file path.
#  - The target will be triggered if one or more patterns match to it.
#
# regex_exclude (Union[List[str], str])
#  - One or more regular expression patterns to exclude. The effect is opposite to `regex`.
#  - The target won't be triggered if one or more file patterns match to it.

processor = ""
name = "noname"
when = ""
path = "."
glob = ""
glob_exclude = ""
regex = ""
regex_exclude = ""


[[target]]  # Properties specific to `make` processor
# `make` processor runs a target in a Makefile.

# target (str)
#  - The make target.
#
# environment (Dict[str, str])
#  - Specify additional environment variables.
#  - By default, r3build inherits the parent's envs.
#
# jobs (int)
#  - Number of parallel jobs. Equivalent to `make -j` option.
#  - If it's zero, r3build will decide N of jobs with multiprocessing.cpu_count().
#
# directory (str)
#  - The directory to read Makefile in. Equivalent to `make -C` option.

target = ""
environment = ""
jobs = 0
directory = ""


[[target]]  # Properties specific to `command` processor
# `command` processor invokes a command.

# command (str)  *REQUIRED*
#  - The command to run. This command will be executed by `subprocess.run` with `shell=True`.
#
# environment (Dict[str, str])
#  - Specify additional environment variables.
#  - By default, r3build inherits the parent's envs.

command = ""
environment = ""


[[target]]  # Properties specific to `pytest` processor
# `pytest` processor runs pytest on a package (directory) or a module (file).

# target (str)  *REQUIRED*
#  - File or directory to run tests.
#  - This string is passed to pytest.main() and also used for reloading Python modules to update test code.
#  - For an advanced use like passing arbitrary arguments to pytest, please use `command` processor.

target = ""
