version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.8.1-buster

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt -r requirements.dev.txt
      - run:
          name: Test
          command: python -m pytest --cov=r3build
      - run:
          name: Coveralls
          command: python -m coveralls

workflows:
  version: 2
  build:
    jobs:
      - test
