# Example: Linux kernel for NXP (formerly Freescale) i.MX28 SoCs w/ cross compile
# Useful for hacking Linux kernel.

[[target]]
name = "Linux"
processor = "make"  # make processor
jobs = 8            # 8 jobs to run parallel

regex = '.*\.[ch]$' # watch .c and .h
when = "modified"   # trigger only on modify

environment.ARCH = "arm"
environment.CROSS_COMPILE = "arm-linux-gnueabi-"

# Alternative way:
#
# [target.environment]
# ARCH = "arm"
# CROSS_COMPILE = "arm-linux-gnueabi-"
