# Example: Linux kernel for NXP i.MX28 SoCs w/ cross compile

[[job]]
  name = "Linux"
  type = "make"      # invokes make
  jobs = 0           # auto-detect the N of job workers
  when = "modified"  # triggers when something is modified
  glob = [           # watch .c, .h, configs
    '*.c',
    '*.h',
    '*config',
  ]

  environment.ARCH = "arm"
  environment.CROSS_COMPILE = "arm-linux-gnueabi-"
