# Example: U-Boot for NXP (formerly Freescale) i.MX28 SoCs w/ cross compile
# Useful for hacking U-Boot.

[[rule]]
name = "U-Boot"
processor = "make"    # make processor
target = "u-boot.sb"  # make target

regex = '.*\.[ch]$'   # watch .c and .h
only = "modified"     # trigger only on modify

environment.ARCH = "arm"
environment.CROSS_COMPILE = "arm-linux-gnueabi-"

# Alternative way:
#
# [rule.environment]
# ARCH = "arm"
# CROSS_COMPILE = "arm-linux-gnueabi-"
