# Example: U-Boot for NXP i.MX28 SoCs w/ cross compile

[[job]]
  name = "U-Boot"
  type = "make"  # invokes make
  target = "u-boot.sb"  # make target
  jobs = 8  # 8 jobs to run parallel

  when = "modified"  # triggers when something is modified
  regex = '.*\.([ch]|dts)$'  # watch .c, .h, and .dts

  environment.ARCH = "arm"
  environment.CROSS_COMPILE = "arm-linux-gnueabi-"
